[BANNER_MESSAGE_SINGLETON]
global_banner.visible = true
global_banner.message = Splunk SSL/TLS Certificate monitoring App is an Enterprise Search App for SSL/TLS Certificate expiration, security compliance, chain auditing, and alerts
global_banner.background_color = blue
global_banner.hyperlink = https://github.com/Tes3awy/splunk-ssl-cert-monitor
global_banner.hyperlink_text = GitHub
