[cert_checker]
rename = cert:ssl:json

[cert:ssl:json]
KV_MODE = json
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
TRUNCATE = 100000
EVENT_BREAKER_ENABLE = true
EVENT_BREAKER = ([\r\n]+)
LB_CHUNK_BREAKER = ([\r\n]+)
category = Network & Security
description = SSL/TLS Certificate monitoring telemetry events
pulldown_type = 1

# Custom App Aliases
FIELDALIAS-target       = dest as target
FIELDALIAS-target_port  = dest_port as target_port

# Official CIM Certificates Data Model Field Mappings
FIELDALIAS-cim_dvc                          = dest as dvc
FIELDALIAS-cim_ssl_subject                  = subject as ssl_subject
FIELDALIAS-cim_ssl_subject_alt_name         = san_list{} as ssl_subject_alt_name
FIELDALIAS-cim_ssl_subject_alt_name_legacy  = san_list{} as ssl_san
FIELDALIAS-cim_san_count                    = san_count as ssl_san_count
FIELDALIAS-cim_ssl_issuer                   = issuer as ssl_issuer
FIELDALIAS-cim_ssl_subject_cn               = subject_cn as ssl_subject_common_name
FIELDALIAS-cim_ssl_issuer_cn                = issuer_cn as ssl_issuer_common_name
FIELDALIAS-cim_ssl_serial                   = serial_number as ssl_serial
FIELDALIAS-cim_ssl_signature_algorithm      = signature_algorithm as ssl_signature_algorithm
FIELDALIAS-cim_ssl_publickey_algo           = signature_algorithm as ssl_publickey_algo
FIELDALIAS-cim_ssl_version                  = negotiated_tls_version AS ssl_version
FIELDALIAS-cim_ssl_cipher                   = cipher AS ssl_cipher
FIELDALIAS-cim_error                        = error AS error_message

# Evaluations
EVAL-ssl_start_time     = coalesce(strptime(valid_from, "%Y-%m-%d %H:%M:%S %Z"), strptime(valid_from, "%Y-%m-%dT%H:%M:%SZ"))
EVAL-ssl_end_time       = coalesce(strptime(valid_to, "%Y-%m-%d %H:%M:%S %Z"), strptime(valid_to, "%Y-%m-%dT%H:%M:%SZ"))
EVAL-ssl_is_valid       = if(status=="VALID" OR status=="EXPIRING_WARNING" OR status=="EXPIRING_CRITICAL", "true", "false")
EVAL-vendor_product     = "Splunk SSL/TLS Certificate Monitor"
