[cert:ssl:json]
KV_MODE = json
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
TRUNCATE = 100000

# CIM Certificates Data Model Aliases & Field Mappings
FIELDALIAS-dest = dest as target
FIELDALIAS-dest_port = dest_port as target_port
FIELDALIAS-ssl_subject = subject_cn as ssl_subject_common_name
FIELDALIAS-ssl_issuer = issuer_cn as ssl_issuer_common_name
FIELDALIAS-ssl_serial = serial_number as ssl_serial
FIELDALIAS-ssl_signature_algorithm = signature_algorithm as ssl_signature_algorithm
FIELDALIAS-ssl_valid_after = valid_from as ssl_start_time
FIELDALIAS-ssl_valid_until = valid_to as ssl_end_time

# Evaluations
EVAL-ssl_is_valid = if(status="VALID" OR status="EXPIRING_WARNING" OR status="EXPIRING_CRITICAL", "true", "false")
EVAL-vendor_product = "Splunk SSL Certificate Monitor"