[install]
is_configured = 0
state = enabled

[id]
name = splunk-app-cert-monitor
version = 1.1.0

[launcher]
author = Osama Abbas
description = Splunk App for SSL/TLS Certificate Expiration and Health Monitoring
version = 1.1.0

[ui]
is_visible = true
label = SSL Certificate Monitor App

[package]
id = splunk-app-cert-monitor
check_for_updates = true