[id]
name = splunk-app-cert-monitor
version = 2.0.0

[install]
is_configured = 0
build = 200
state = enabled

[package]
id = splunk-app-cert-monitor
check_for_updates = false

[ui]
is_visible = true
label = SSL/TLS Certificate Monitor App

[launcher]
author = Osama Abbas
description = Enterprise Search App for SSL/TLS Certificate expiration, security compliance, chain auditing, and alerts.
version = 2.0.0