[id]
name = splunk-app-cert-monitor
version = 2.2.0

[author=Osama Abbas]
email = osama.abbas@bmbgroup.com
company = bmbgroup

[install]
is_configured = 0
build = 202610101112
state = enabled
allows_disable = true

[package]
id = splunk-app-cert-monitor
check_for_updates = 0

[ui]
label = SSL/TLS Certificate Monitor App
is_visible = true
show_in_nav = true

[launcher]
author = Osama Abbas
description = A Splunk Enterprise App for SSL/TLS Certificate expiration, security compliance, chain auditing, and alerts.
version = 2.2.0

[triggers]
reload.splunk-app-cert-monitor = simple
