[install]
is_configured = 0
state = enabled

[id]
name = TA-cert-monitor
version = 1.3.2

[launcher]
author = Osama Abbas
description = Technology Add-on for SSL/TLS Certificate Monitoring
version = 1.3.2

[ui]
is_visible = false
label = SSL Certificate Monitor Add-on

[package]
id = TA-cert-monitor
check_for_updates = true