[cert_checker]
python.version = python3
python.required = 3.13

[cert_checker://internal_api_gateway]
target_host = example.com
port = 8443
sni = api.example.com
interval = 86400
verify_cert = true
timeout = 5
index = main
python.version = python3
python.required = 3.13

[cert_checker://public_website]
target_host = example.org
port = 443
sni = example.org
interval = 43200
index = main
python.version = python3
python.required = 3.13